#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "BlindsControl"
  https://create.arduino.cc/cloud/things/b0b34375-504c-43f1-bea1-90b41cbe0340 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool btnClose_cv;
  bool btnOpen_cv;
  bool isOpen_cv;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Stepper.h>

const int buttonClose_Pin = 2;
const int buttonOpen_Pin = 3;
int statusLED_Pin = LED_BUILTIN;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(statusLED_Pin, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  isOpen_cv = digitalRead(statusLED_Pin);
  Serial.print("Estado del LED: ");
  Serial.println(isOpen_cv);
  delay(1000);
}

/*
  Since BtnOpenCv is READ_WRITE variable, onBtnOpenCvChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBtnOpenCvChange()  {
  // Add your code here to act upon BtnOpenCv change
  if (isOpen_cv == pdTRUE){
    Serial.println("Already Open.");  
  }else {
    digitalWrite(statusLED_Pin, HIGH);
    Serial.println("Openning...");
    delay(500);
    Serial.println("Open");
  }
}

/*
  Since BtnCloseCv is READ_WRITE variable, onBtnCloseCvChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBtnCloseCvChange()  {
  // Add your code here to act upon BtnCloseCv change
  if (isOpen_cv == pdFALSE){
    Serial.println("Already Close.");
  }else {
    digitalWrite(statusLED_Pin, LOW);
    Serial.println("Closing...");
    delay(500);
    Serial.println("Close"); 
  }
}