// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "86f211fa-d740-4295-b561-bb8007f6ee88";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBtnCloseCvChange();
void onBtnOpenCvChange();

bool btnClose_cv;
bool btnOpen_cv;
bool isOpen_cv;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(btnClose_cv, READWRITE, ON_CHANGE, onBtnCloseCvChange);
  ArduinoCloud.addProperty(btnOpen_cv, READWRITE, ON_CHANGE, onBtnOpenCvChange);
  ArduinoCloud.addProperty(isOpen_cv, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
